title: Jeong byeong hun
description: Android Developer
site_title: 'Jeong byeong hun - Portfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Jeong-byeong-hun
blog_url: https://github.com/Jeong-Byeong-hun
email: j95hun@naver.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/asd.jpg

# Google Analytics ID
google_analytics: 